apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/islamr12/argocd-openshift
    targetRevision: main
    path: bubble-animation/application-manifest   # verify this path in GitHub
  destination:
    server: https://kubernetes.default.svc
    namespace: bubble-animation
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true